import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const PrivacyPolicy = () => {
  return (
    <>
      <Header />
      <div className="min-h-screen bg-background py-12">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="bg-card rounded-lg shadow-md p-8">
            <h1 className="text-4xl font-bold mb-8 text-foreground">Privacy Policy</h1>
            
            <div className="prose prose-gray max-w-none space-y-6 text-foreground">
              <p className="text-sm text-muted-foreground">
                This document (hereinafter referred to as "Privacy Policy") is an electronic record in terms of existing and applicable Information Technology laws and allied rules, regulations, directions, and guidelines, including amended provisions pertaining to electronic records in various allied statutes as amended pursuant to the Information Technology Act, 2000 ("IT Act"). This electronic record has been generated by a computer system and does not require any authentication.
              </p>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">1. Preliminary Information</h2>
                <p>
                  The Site www.MaxDSA.com and/or any other associate website (hereinafter referred to as "Site" or "Website") or MaxDSA (the "Mobile Application") is subject to the terms of a legal agreement between the user of the Website/Mobile Application and MAXDSA Business Services Private Limited (hereinafter referred to as the "Company"). The Company is incorporated under the provisions of the Companies Act, 2013, having its registered office at 4A, SreeVatsa Swagat Apartment, Patel Road, Ram Nagar, Coimbatore 641009.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Definitions</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>The term "User", "Client", or "You" or any other variant of the said pronoun shall refer to the user who is browsing this Site.</li>
                  <li>The term "Company" shall refer to MAXDSA Business Services Private Limited and/or its affiliates/subsidiary companies.</li>
                  <li>The term "Site" or "Website" refers to www.MaxDSA.com and shall include other websites if any owned and monitored by the Company.</li>
                  <li>The term "Information" or "Personal Information" provided by the User shall include any personal information or data, sensitive personal data, or any other information so supplied by the User, in accordance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data) Rules, 2011, and allied rules and regulations.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Information Collection</h2>
                <p>
                  Through the Website/Mobile Application, the Company enables Users to avail services pertaining to inter alia loans, mortgage, financing, and financial instruments such as personal loans, home loans, unsecured business loans, loans against property, and other allied matters related thereto.
                </p>
                <p className="font-semibold">The Personal Information collected from the User while accessing the Website/Mobile Application includes:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Name (including the first and last name) of the User</li>
                  <li>Email address of the User</li>
                  <li>Contact details (including the mobile phone number) of the User</li>
                  <li>Zip/Postal code of the User's location</li>
                  <li>The demographic profile of the User including inter alia the User's age, gender, occupation, and address</li>
                  <li>Financial information including, but not limited to, the User's salary</li>
                  <li>The User's preference in so far as the loan services offered by the Website/Mobile Application are concerned including inter alia preferences pertaining to housing loans, personal loans, loans against property, business loans, and the like</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">2. Reasonable Security Practices and Procedures</h2>
                <p>
                  The Company has in place reasonable measures to protect and safeguard the information provided by the User on its interface in accordance with the Information Technology Act, 2000 and its allied Rules and Regulations. However, the User indemnifies the Company from any kind of liability in case of any loss of data/information belonging to the User, resulting from an event which could not have been prevented by the exercise of prudence on the part of the Company.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">3. Use of Information</h2>
                <p>The Company may use the information provided by the User for the following purposes:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>To provide and improve services offered through the Website/Mobile Application</li>
                  <li>To process loan applications and facilitate financial services</li>
                  <li>To communicate with Users regarding their applications and services</li>
                  <li>To comply with legal and regulatory requirements</li>
                  <li>To prevent fraud and enhance security</li>
                  <li>For marketing and promotional activities (with User consent)</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">4. Disclosure of Information</h2>
                <p>
                  The Company may disclose User information to third parties including financial institutions, banks, and NBFCs for the purpose of facilitating loan applications and related services. The Company may also disclose information when required by law or to protect the rights, property, or safety of the Company, its users, or others.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">5. Cookies and Tracking</h2>
                <p>
                  The Website/Mobile Application will automatically receive and collect certain anonymous information in standard usage logs through its webserver, including computer-identification information obtained from "Cookies" sent to the User's browser. This helps improve user experience and analyze website usage patterns.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">6. User Rights</h2>
                <p>Users have the right to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Access their personal information held by the Company</li>
                  <li>Request correction of inaccurate information</li>
                  <li>Request deletion of personal information (subject to legal requirements)</li>
                  <li>Withdraw consent for data processing (where applicable)</li>
                  <li>Lodge complaints with relevant authorities regarding data privacy concerns</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">7. Data Retention</h2>
                <p>
                  The Company will retain User information for as long as necessary to fulfill the purposes outlined in this Privacy Policy, comply with legal obligations, resolve disputes, and enforce agreements.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">8. Changes to Privacy Policy</h2>
                <p>
                  The Company reserves the right to modify this Privacy Policy at any time. Changes will be effective immediately upon posting on the Website/Mobile Application. Users are encouraged to review this Privacy Policy periodically for any updates.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">9. Contact Information</h2>
                <p>
                  For any questions or concerns regarding this Privacy Policy or the handling of personal information, please contact:
                </p>
                <div className="bg-muted p-4 rounded-lg">
                  <p><strong>MAXDSA Business Services Private Limited</strong></p>
                  <p>4A, SreeVatsa Swagat Apartment, Patel Road</p>
                  <p>Ram Nagar, Coimbatore 641009</p>
                  <p>Email: partner@maxdsa.com</p>
                  <p>Phone: +91 9042385395</p>
                </div>
              </section>

              <section className="mt-8 pt-6 border-t border-border">
                <p className="text-sm text-muted-foreground">
                  Last Updated: {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default PrivacyPolicy;
