import Header from "@/components/shared/Header";
import Footer from "@/components/shared/Footer";

const TermsOfUse = () => {
  return (
    <>
      <Header />
      <div className="min-h-screen bg-background py-12">
        <div className="mx-auto max-w-4xl px-4 sm:px-6 lg:px-8">
          <div className="bg-card rounded-lg shadow-md p-8">
            <h1 className="text-4xl font-bold mb-8 text-foreground">Terms of Use</h1>
            
            <div className="prose prose-gray max-w-none space-y-6 text-foreground">
              <p className="text-sm text-muted-foreground">
                This document (hereinafter referred to as "Terms of Use/TOU") is an electronic record in terms of existing and applicable Information Technology laws and the amended provisions thereto pertaining to electronic records in various allied statutes as amended pursuant to the Information Technology laws. This electronic record has been generated by a computer system and does not require any authentication.
              </p>

              <p>
                The Site https://www.MaxDSA.com and/or any other associate website (hereinafter referred to as "Site" or "Website") or MAXDSA (the "Mobile Application") is subject to the terms of a legal agreement between the user of the Website/Mobile Application and MAXDSA Business Services Private Limited (hereinafter referred to as the "Company"). The Company is incorporated under the provisions of the Companies Act, 2013, having its registered office at 4A, SreeVatsa Swagat Apartment, Patel Road, Ram Nagar, Coimbatore 641009.
              </p>

              <p>
                The following terms and conditions will be deemed to have been accepted by you ("User") on mere visitation and/or usage of the services of this Website/Mobile Application. You are requested to read them carefully before you visit/use the services of this Website/Mobile Application.
              </p>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Definitions</h2>
                <ul className="list-disc pl-6 space-y-2">
                  <li>The term "User", "Client" or "You" (or any variant of the said pronoun) shall refer to the user who is browsing or using the services of this Website/Mobile Application.</li>
                  <li>The term "Company" shall refer to MAXDSA Business Services Private Limited and/or its affiliates/subsidiary companies.</li>
                  <li>The term "Site" or "Website" refers to https://www.MaxDSA.com and other websites, if any, owned, monitored by, or associated with the Company and includes the software, materials, text, images, graphics, video, audio, and applications on such Site.</li>
                  <li>The terms "Content", "Technology" and "Material" shall refer to all information, data, software, and other resources available on the Website/Mobile Application.</li>
                  <li>The term "Product" or "Services" refers to access to information primarily about Financial and Insurance products and services including but not restricted to General Insurance, Life Insurance products and related services (including but not limited to renewals) provided by the Company to the User.</li>
                  <li>The term "Personal Information" and "Information" provided by the User shall include any personal information or data, sensitive personal data, or any other information so provided by the User to the Company, in accordance with the Information Technology (Reasonable Security Practices and Procedures and Sensitive Personal Data) Rules, 2011, and allied rules and regulations.</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Description of Services</h2>
                <p>
                  The Company, through its Website/Mobile Application, provides Users with access to information, resources, and services related to financial products including but not limited to:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Personal loans</li>
                  <li>Home loans</li>
                  <li>Business loans</li>
                  <li>Loans against property</li>
                  <li>Kirana store loans</li>
                  <li>Insurance products</li>
                  <li>Financial advisory services</li>
                </ul>
                <p>
                  The Company acts as a Direct Selling Agent (DSA) and facilitates connections between Users and financial institutions, banks, and NBFCs.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">User Obligations</h2>
                <p>By using the Website/Mobile Application, you agree to:</p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Provide accurate, current, and complete information as requested</li>
                  <li>Maintain the confidentiality of your account credentials</li>
                  <li>Not use the services for any unlawful purpose</li>
                  <li>Not interfere with or disrupt the Website/Mobile Application or servers</li>
                  <li>Not attempt to gain unauthorized access to any part of the Website/Mobile Application</li>
                  <li>Comply with all applicable laws and regulations</li>
                  <li>Not transmit any viruses, malware, or harmful code</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Intellectual Property Rights</h2>
                <p>
                  All content, materials, information, software, products, and services included on or available through the Website/Mobile Application, including but not limited to text, graphics, logos, images, audio clips, digital downloads, and software, are the property of the Company or its content suppliers and are protected by Indian and international copyright, trademark, patent, trade secret, and other intellectual property laws.
                </p>
                <p>
                  Users may not modify, copy, distribute, transmit, display, perform, reproduce, publish, license, create derivative works from, transfer, or sell any information, software, products, or services obtained from the Website/Mobile Application without prior written consent from the Company.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Limitation of Liability</h2>
                <p>
                  The Company shall not be liable for any direct, indirect, incidental, special, consequential, or punitive damages resulting from:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Your access to or use of, or inability to access or use, the Website/Mobile Application</li>
                  <li>Any conduct or content of any third party on the Website/Mobile Application</li>
                  <li>Any content obtained from the Website/Mobile Application</li>
                  <li>Unauthorized access, use, or alteration of your transmissions or content</li>
                  <li>Loan application rejections by financial institutions</li>
                  <li>Changes in interest rates or terms offered by financial institutions</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Third-Party Links and Services</h2>
                <p>
                  The Website/Mobile Application may contain links to third-party websites or services that are not owned or controlled by the Company. The Company has no control over and assumes no responsibility for the content, privacy policies, or practices of any third-party websites or services. You acknowledge and agree that the Company shall not be responsible or liable, directly or indirectly, for any damage or loss caused or alleged to be caused by or in connection with the use of or reliance on any such content, goods, or services available on or through any such websites or services.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Indemnification</h2>
                <p>
                  You agree to indemnify, defend, and hold harmless the Company, its officers, directors, employees, agents, and affiliates from and against any and all claims, damages, obligations, losses, liabilities, costs, or debt, and expenses (including but not limited to attorney's fees) arising from:
                </p>
                <ul className="list-disc pl-6 space-y-2">
                  <li>Your use of and access to the Website/Mobile Application</li>
                  <li>Your violation of any term of these Terms of Use</li>
                  <li>Your violation of any third-party right, including without limitation any copyright, property, or privacy right</li>
                  <li>Any claim that your content caused damage to a third party</li>
                </ul>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Disclaimer of Warranties</h2>
                <p>
                  The Website/Mobile Application and all information, content, materials, products, and services included on or otherwise made available to you through the Website/Mobile Application are provided on an "AS IS" and "AS AVAILABLE" basis. The Company makes no representations or warranties of any kind, express or implied, as to the operation of the Website/Mobile Application or the information, content, materials, products, or services included on or otherwise made available to you through the Website/Mobile Application.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Termination</h2>
                <p>
                  The Company may terminate or suspend your access to the Website/Mobile Application immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach these Terms of Use. Upon termination, your right to use the Website/Mobile Application will immediately cease.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Governing Law and Jurisdiction</h2>
                <p>
                  These Terms of Use shall be governed by and construed in accordance with the laws of India. Any disputes arising out of or in connection with these Terms of Use shall be subject to the exclusive jurisdiction of the courts located in Coimbatore, Tamil Nadu.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Changes to Terms of Use</h2>
                <p>
                  The Company reserves the right, at its sole discretion, to modify or replace these Terms of Use at any time. If a revision is material, we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be determined at the sole discretion of the Company.
                </p>
                <p>
                  By continuing to access or use the Website/Mobile Application after revisions become effective, you agree to be bound by the revised terms. If you do not agree to the new terms, you are no longer authorized to use the Website/Mobile Application.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Severability</h2>
                <p>
                  If any provision of these Terms of Use is held to be invalid or unenforceable by a court, the remaining provisions of these Terms of Use will remain in effect.
                </p>
              </section>

              <section className="space-y-4">
                <h2 className="text-2xl font-semibold text-foreground">Contact Information</h2>
                <p>
                  For any questions or concerns regarding these Terms of Use, please contact:
                </p>
                <div className="bg-muted p-4 rounded-lg">
                  <p><strong>MAXDSA Business Services Private Limited</strong></p>
                  <p>4A, SreeVatsa Swagat Apartment, Patel Road</p>
                  <p>Ram Nagar, Coimbatore 641009</p>
                  <p>Email: partner@maxdsa.com</p>
                  <p>Phone: +91 9042385395</p>
                </div>
              </section>

              <section className="mt-8 pt-6 border-t border-border">
                <p className="text-sm text-muted-foreground">
                  Last Updated: {new Date().toLocaleDateString('en-IN', { year: 'numeric', month: 'long', day: 'numeric' })}
                </p>
              </section>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
};

export default TermsOfUse;
